import type { GenerateConfig } from "../shared/types";
import { resolveLibrary, getScale, scaleSteps, nearestStep, buildSemanticTokens } from "../data";
import { hexToRgb } from "./color";

const FONT_REGULAR: FontName = { family: "Inter", style: "Regular" };
const FONT_BOLD: FontName = { family: "Inter", style: "Bold" };

async function loadDocFonts(): Promise<{ regular: FontName; bold: FontName }> {
  try {
    await figma.loadFontAsync(FONT_REGULAR);
    await figma.loadFontAsync(FONT_BOLD);
    return { regular: FONT_REGULAR, bold: FONT_BOLD };
  } catch {
    const r: FontName = { family: "Roboto", style: "Regular" };
    const b: FontName = { family: "Roboto", style: "Bold" };
    await figma.loadFontAsync(r);
    await figma.loadFontAsync(b);
    return { regular: r, bold: b };
  }
}

function text(content: string, font: FontName, size: number, color = "#1e293b"): TextNode {
  const node = figma.createText();
  node.fontName = font;
  node.fontSize = size;
  node.characters = content;
  node.fills = [{ type: "SOLID", color: hexToRgb(color) }];
  return node;
}

function vstack(name: string, gap: number, padding = 0): FrameNode {
  const f = figma.createFrame();
  f.name = name;
  f.layoutMode = "VERTICAL";
  f.itemSpacing = gap;
  f.paddingTop = f.paddingBottom = f.paddingLeft = f.paddingRight = padding;
  f.fills = [];
  f.counterAxisSizingMode = "AUTO";
  f.primaryAxisSizingMode = "AUTO";
  return f;
}

function hstack(name: string, gap: number): FrameNode {
  const f = vstack(name, gap);
  f.layoutMode = "HORIZONTAL";
  return f;
}

function swatch(hex: string, label: string, sub: string, fonts: { regular: FontName }): FrameNode {
  const cell = vstack(`swatch ${label}`, 4);
  const rect = figma.createRectangle();
  rect.resize(72, 48);
  rect.cornerRadius = 6;
  rect.fills = [{ type: "SOLID", color: hexToRgb(hex) }];
  rect.strokes = [{ type: "SOLID", color: hexToRgb("#e2e8f0") }];
  rect.strokeWeight = 1;
  cell.appendChild(rect);
  cell.appendChild(text(label, fonts.regular, 11, "#0f172a"));
  cell.appendChild(text(sub, fonts.regular, 10, "#64748b"));
  return cell;
}

export async function printDocs(config: GenerateConfig): Promise<FrameNode> {
  const fonts = await loadDocFonts();
  const lib = resolveLibrary(config);

  const root = vstack("AM Gym — Design Foundations", 32, 48);
  root.fills = [{ type: "SOLID", color: hexToRgb("#ffffff") }];
  root.cornerRadius = 16;

  root.appendChild(text("Design Foundations", fonts.bold, 32, "#0f172a"));
  root.appendChild(text(`${lib.label} • generated by AM Gym`, fonts.regular, 14, "#64748b"));

  // --- Color palette ---
  const colorSection = vstack("Color Palette", 16);
  colorSection.appendChild(text("Color Palette", fonts.bold, 20));
  for (const scaleName of config.selectedScales) {
    const scale = getScale(lib, scaleName);
    if (!scale) continue;
    const row = vstack(scale.label, 8);
    row.appendChild(text(scale.label, fonts.bold, 13));
    const swatches = hstack(`${scale.label} swatches`, 8);
    for (const step of scaleSteps(scale)) {
      if (scale.shades[step]) swatches.appendChild(swatch(scale.shades[step], step, scale.shades[step], fonts));
    }
    row.appendChild(swatches);
    colorSection.appendChild(row);
  }
  root.appendChild(colorSection);

  // --- Semantic tokens ---
  if (config.includeSemantic) {
    const tokens = config.semantic.length ? config.semantic : buildSemanticTokens(config.primaryScale, config.selectedScales);
    const sec = vstack("Semantic Tokens", 12);
    sec.appendChild(text("Semantic Tokens", fonts.bold, 20));
    const grid = hstack("semantic swatches", 8);
    grid.layoutWrap = "WRAP";
    grid.counterAxisSizingMode = "FIXED";
    grid.resize(900, 10);
    for (const t of tokens) {
      const l = getScale(lib, t.light.scale);
      if (l) grid.appendChild(swatch(l.shades[nearestStep(scaleSteps(l), t.light.step)], t.label, t.name, fonts));
    }
    sec.appendChild(grid);
    root.appendChild(sec);
  }

  // --- Typography ---
  if (config.includeTypography && config.typography.length) {
    const sec = vstack("Typography", 12);
    sec.appendChild(text("Typography", fonts.bold, 20));
    for (const t of config.typography) {
      const sample = text(`${t.label} — ${t.fontSize}/${t.lineHeight} · ${t.fontWeight}`, fonts.regular, Math.min(t.fontSize, 48));
      sec.appendChild(sample);
    }
    root.appendChild(sec);
  }

  // --- Spacing ---
  if (config.includeSpacing && config.spacing.length) {
    const sec = vstack("Spacing & Size", 8);
    sec.appendChild(text("Spacing & Size", fonts.bold, 20));
    for (const s of config.spacing) {
      const rowf = hstack(s.name, 12);
      rowf.counterAxisAlignItems = "CENTER";
      rowf.appendChild(text(`${s.name} (${s.value})`, fonts.regular, 12));
      const bar = figma.createRectangle();
      bar.resize(Math.max(s.value, 1), 12);
      bar.cornerRadius = 2;
      bar.fills = [{ type: "SOLID", color: hexToRgb("#6366f1") }];
      rowf.appendChild(bar);
      sec.appendChild(rowf);
    }
    root.appendChild(sec);
  }

  // Position near the current viewport and focus it.
  root.x = figma.viewport.center.x - 500;
  root.y = figma.viewport.center.y - 300;
  figma.currentPage.appendChild(root);
  figma.viewport.scrollAndZoomIntoView([root]);
  return root;
}
