import type { ExportFormat, GenerateConfig } from "../shared/types";
import { resolveLibrary, getScale, scaleSteps, nearestStep, buildSemanticTokens } from "../data";

interface FlatTokens {
  colors: Record<string, string>; // "blue-500" -> hex
  semanticLight: Record<string, string>;
  semanticDark: Record<string, string>;
  spacing: Record<string, number>;
  typography: Record<string, { fontSize: number; lineHeight: number; fontWeight: number; letterSpacing: number }>;
}

function collect(config: GenerateConfig): FlatTokens {
  const lib = resolveLibrary(config);
  const out: FlatTokens = { colors: {}, semanticLight: {}, semanticDark: {}, spacing: {}, typography: {} };

  for (const scaleName of config.selectedScales) {
    const scale = getScale(lib, scaleName);
    if (!scale) continue;
    for (const step of scaleSteps(scale)) {
      if (scale.shades[step]) out.colors[`${scaleName}-${step}`] = scale.shades[step];
    }
  }

  if (config.includeSemantic) {
    const tokens = config.semantic.length ? config.semantic : buildSemanticTokens(config.primaryScale, config.selectedScales);
    for (const t of tokens) {
      const l = getScale(lib, t.light.scale);
      const d = getScale(lib, t.dark.scale);
      if (l) out.semanticLight[t.name] = l.shades[nearestStep(scaleSteps(l), t.light.step)];
      if (d) out.semanticDark[t.name] = d.shades[nearestStep(scaleSteps(d), t.dark.step)];
    }
  }

  if (config.includeSpacing) for (const s of config.spacing) out.spacing[s.name] = s.value;
  if (config.includeTypography)
    for (const t of config.typography)
      out.typography[t.name] = {
        fontSize: t.fontSize,
        lineHeight: t.lineHeight,
        fontWeight: t.fontWeight,
        letterSpacing: t.letterSpacing,
      };

  return out;
}

function toCss(t: FlatTokens): string {
  const lines: string[] = [":root {"];
  for (const [k, v] of Object.entries(t.colors)) lines.push(`  --color-${k}: ${v};`);
  for (const [k, v] of Object.entries(t.semanticLight)) lines.push(`  --${k}: ${v};`);
  for (const [k, v] of Object.entries(t.spacing)) lines.push(`  --${k}: ${v}px;`);
  for (const [k, v] of Object.entries(t.typography)) {
    lines.push(`  --font-${k}-size: ${v.fontSize}px;`);
    lines.push(`  --font-${k}-line-height: ${v.lineHeight}px;`);
    lines.push(`  --font-${k}-weight: ${v.fontWeight};`);
    lines.push(`  --font-${k}-letter-spacing: ${v.letterSpacing}px;`);
  }
  lines.push("}");
  if (Object.keys(t.semanticDark).length) {
    lines.push("", '[data-theme="dark"] {');
    for (const [k, v] of Object.entries(t.semanticDark)) lines.push(`  --${k}: ${v};`);
    lines.push("}");
  }
  return lines.join("\n");
}

function toJs(t: FlatTokens): string {
  return `// Design tokens generated by AM Gym — Design Foundations
export const tokens = ${JSON.stringify(
    {
      colors: t.colors,
      semantic: { light: t.semanticLight, dark: t.semanticDark },
      spacing: t.spacing,
      typography: t.typography,
    },
    null,
    2,
  )};

export default tokens;
`;
}

function toJson(t: FlatTokens): string {
  // W3C-style design tokens ($value / $type).
  const doc: Record<string, unknown> = {};
  const color: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(t.colors)) color[k] = { $value: v, $type: "color" };
  doc.color = color;
  if (Object.keys(t.semanticLight).length) {
    const sem: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(t.semanticLight)) {
      sem[k] = { $value: v, $type: "color", $extensions: { dark: t.semanticDark[k] } };
    }
    doc.semantic = sem;
  }
  if (Object.keys(t.spacing).length) {
    const sp: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(t.spacing)) sp[k] = { $value: `${v}px`, $type: "dimension" };
    doc.spacing = sp;
  }
  if (Object.keys(t.typography).length) {
    const ty: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(t.typography))
      ty[k] = {
        $type: "typography",
        $value: {
          fontSize: `${v.fontSize}px`,
          lineHeight: `${v.lineHeight}px`,
          fontWeight: v.fontWeight,
          letterSpacing: `${v.letterSpacing}px`,
        },
      };
    doc.typography = ty;
  }
  return JSON.stringify(doc, null, 2);
}

export function exportTokens(format: ExportFormat, config: GenerateConfig): { filename: string; content: string } {
  const t = collect(config);
  switch (format) {
    case "css":
      return { filename: "tokens.css", content: toCss(t) };
    case "js":
      return { filename: "tokens.js", content: toJs(t) };
    case "json":
      return { filename: "tokens.json", content: toJson(t) };
  }
}
